[loggers]
keys=root,uvicorn,uvicorn.error,uvicorn.access

[handlers]
keys=file

[formatters]
keys=default

### LOGGERS ###

[logger_root]
level=INFO
handlers=file
qualname=root

[logger_uvicorn]
level=INFO
handlers=file
propagate=1
qualname=uvicorn

[logger_uvicorn.error]
level=INFO
handlers=file
propagate=1
qualname=uvicorn.error

[logger_uvicorn.access]
level=INFO
handlers=file
propagate=1
qualname=uvicorn.access

### HANDLER ###

[handler_file]
class=logging.FileHandler
level=INFO
formatter=default
args=('/var/log/app.log','a')

### FORMATTER ###

[formatter_default]
format=%(asctime)s %(levelname)s %(message)s
